BIBLIOGRAPHY = ('@book{wagon,\n'
 '  title={The Banach-Tarski Paradox},\n'
 '  author={Stan Wagon},\n'
 '  isbn={0-521-45704-1},\n'
 '  year={1994},\n'
 '  publisher={Cambridge University Press},\n'
 '  keywords = {math}\n'
 '}\n'
 '\n'
 ' \n'
 ' @book{dummfoote,\n'
 '    author    = "David S. Dummit \\& Richard M. Foote",\n'
 '    title     = "Abstract Algebra",\n'
 '    isbn      = {0-471-43334-9},\n'
 '    year      = {2003},\n'
 '    publisher = "John Wiley \\& Sons",\n'
 '    address   = "U.S.A",\n'
 '    keywords  = "math"\n'
 '}\n'
 '\n'
 '@book{eves,\n'
 '    author    = "H. Eves",\n'
 '    title     = "A Survey of Geometry",\n'
 '    year      = {1963},\n'
 '    volume    = {1},\n'
 '    address   = "Boston",\n'
 '    publisher = "Allyn and Bacon",\n'
 '    keywords  = "math"\n'
 '}\n'
 '\n'
 '@article{addison,\n'
 '    author  = "J. W. Addison",\n'
 '    title   = "Obituary for Alfred Tarski",\n'
 '    year    = "1983",\n'
 '    journal = "California Monthly 94(2)",\n'
 '    keywords  = "paradox"\n'
 '}\n'
 '\n'
 '@article{sury,\n'
 '    author  = "B Sury",\n'
 '    title   = '
 '"\\href{http://www.ias.ac.in/article/fulltext/reso/022/10/0943-0953}{Unearthing '
 'the Banach–Tarski Paradox}",\n'
 '    year    = "2017",\n'
 '    journal = "Resonance",\n'
 '    keywords  = "paradox"\n'
 '}\n'
 '\n'
 '@article{halvohansen,\n'
 '    author  = "Esben Bistrup Halvorsen \\& Lars Hougaard hansen",\n'
 '    title   = "The Banach–Tarski Paradox",\n'
 '    year    = "2000",\n'
 '    keywords  = "paradox"\n'
 '}')