SECTIONS = {'1': '\\subsection{Ordinary Induction}\n'
      '\\begin{exercise} Prove, for all natural numbers $n$, that \n'
      '\\begin{equation} \\mathcolor{orange}{\\sum_{k=0}^n k = 1 + 2 + 3 + '
      '\\cdots + n = \\dfrac{n(n+1)}{2}}\n'
      '\\label{eq_Pn}\\end{equation}\n'
      '\\end{exercise}\n'
      '\n'
      '\\begin{proof}\n'
      'We prove this by induction on $n\\in\\N$.  In the base case, $n=0$, and '
      '\\ref{eq_Pn} becomes\n'
      '$$\\sum_{k=0}^n k = \\sum_{k=0}^0 k = 0 = \\dfrac{0(1)}{2} = '
      '\\frac{n(n+1)}{2}$$\n'
      'Now, let $n>0$ be arbitrary, and assume \\ref{eq_Pn}.\n'
      '\n'
      'We show $\\displaystyle \\sum_{k=0}^{n+1} k = \\dfrac{(n+1)(n+2)}{2}$.\n'
      'To that end note \n'
      '\\begin{align*}\n'
      '\t\\mathcolor{red}{\\sum_{k=0}^{n+1}} k &= \\left(\\sum_{k=0}^{n} '
      'k\\right) + (n+1) &\\mbox{(sum definition)}\\\\\n'
      '\t&= \\frac{n(n+1)}{2} + (n+1) &\\mbox{(induction hypothesis)}\n'
      '\t\\\\\n'
      '\t&= \\frac{n(n+1)}{2} + \\frac{2n+2}{2} &\\mbox{(common denominator)}\n'
      '\t\\\\\n'
      '\t&= \\frac{n^2 +n}{2} + \\frac{2n+2}{2} &\\mbox{(distribute)}\n'
      '\t\\\\\n'
      '\t&= \\frac{n^2 +3n + 2}{2} &\\mbox{(combine like terms)}\n'
      '\t\\\\\n'
      '\t&= \\mathcolor{brown}{\\frac{(n+1)(n+2)}{2}} & \\mbox{(factor the '
      'numerator)}\\\\\n'
      '\\end{align*}\n'
      '\n'
      'In all cases, \\ref{eq_Pn} is true, so $\\forall n\\in \\N$, \n'
      '$\\Disp \\sum_{k=0}^n k = \\dfrac{n(n+1)}{2}$\n'
      '\\end{proof}\n'
      '\\begin{theorem}\n'
      '$\\N$ is unbounded.\n'
      '\\end{theorem}\n'
      '\\begin{proof}\n'
      '\\lipsum[1]\n'
      '\\end{proof}\n'
      '\\begin{remark}\n'
      'Hey there is a Remark....!\n'
      '\\end{remark}\n'
      '\n',
 '2': 'Here, I try some of my \\textcolor{orange}{redefine} symbols:\n'
      'Let $\\cvec{x}$ be a vector in $\\R^2$ for example let '
      '$\\cvec{x}=3\\ihat+8\\jhat+2\\khat$ and let $\\spn (A)=\\emptyset$ For '
      'm by n use $\\mbyn{m}{n}$ also $\\mbyn{3}{4}$\\\\\n'
      'Some Equation:\n'
      '\n'
      '$$f^{(k)}(a)\\ \\mathcolor{blue}{n(\\gamma, a)} = '
      '\\frac{k!}{\\mathcolor{purple}{2\\pi '
      'i}}\\mathcolor{green}{\\int_{\\gamma}}\\frac{f(z)}{(z-a)^{k+1}} \\diff '
      'z$$\n'
      'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Ut purus '
      'elit, vestibulum ut, placerat ac, adipiscing vitae, felis. Curabitur '
      'dictum gravida mauris. Nam arcu libero, nonummy eget, consectetuer id, '
      'vulputate a, magna. Donec vehicula augue eu neque.\n'
      'Function Definitions:\n'
      '\\[\n'
      'f(n) = \\begin{cases} n/2, & \\mbox{if } n\\mbox{ is even} \\\\\n'
      '\t 3n+1, & \\mbox{if } n\\mbox{ is odd} \\end{cases}\n'
      '\\]\n'
      ' \n'
      'nonummy eget, consectetuer id, vulputate a, magna. Donec vehicula augue '
      'eu neque. Pel- lentesque habitant morbi tristique senectus et netus et '
      'malesuada fames ac turpis egestas. Mauris ut leo. Cras viverra metus \n'
      '  \n'
      '\\[\n'
      ' \\lim_{x\\to 0}{\\frac{e^x-1}{2x}}\n'
      ' \\overset{\\left[\\frac{0}{0}\\right]}{\\underset{\\mathrm{H}}{=}}\n'
      ' \\lim_{x\\to 0}{\\frac{e^x}{2}}={\\frac{1}{2}}\n'
      '\\]\n'
      'Also Note the followings:\n'
      '\\[\n'
      ' z = \\overbrace{\n'
      '   \\underbrace{x}_\\text{\\textcolor{blue}{real}} + i\n'
      '   \\underbrace{y}_\\text{imaginary}\n'
      '  }^\\text{\\textcolor{red}{complex number}}\n'
      '\\]\n'
      'Matrices:\n'
      '\\[\n'
      'M = \\begin{bmatrix}\n'
      ' 0 & \\cdots & 0 \\\\\n'
      '  \\vdots & \\ddots & \\vdots \\\\ \n'
      '  0 & \\cdots & 0 \n'
      '  \\end{bmatrix}\n'
      '\\]\n'
      'nonummy eget, consectetuer id, vulputate a, magna. Donec vehicula augue '
      'eu neque. Pel- lentesque habitant morbi tristique senectus et netus et '
      'malesuada fames ac turpis egestas. Mauris ut leo. Cras viverra metus \n'
      '\n'
      '%%%%%%\n'
      ' \\subsection{Complicated Math Equations}\n'
      ' \n'
      '  \\[\n'
      '    \\mathcal L_{\\mathcal T}(\\vec{\\lambda})\n'
      '    = \\sum_{(\\mathbf{x},\\mathbf{s})\\in \\mathcal T}\n'
      '       \\log P(\\mathbf{s}\\mid\\mathbf{x}) - \\sum_{i=1}^m\n'
      '       \\frac{\\lambda_i^2}{2\\sigma^2}\n'
      '  \\]\n'
      '\n'
      '\\lipsum[1]\n'
      '\n'
      '\n'
      '\\[\n'
      "g'(u_t, x_{t-1}) \\coloneqq \\frac{\\partial g(u_t, u_{t-1})}{\\partial "
      'x_{t-1}}\n'
      '\\]\n'
      '\n'
      'Also, we can type the following:\n'
      '\\begin{align*}\n'
      'S(\\mathcolor{blue}{\\omega}) \n'
      '&= \\frac{\\alpha g^2}{\\omega^5} e^{[ -0.74\\bigl\\{\\frac{\\omega '
      'U_\\omega 19.5}{g}\\bigr\\}^{\\!-4}\\,]} \\\\\n'
      '&= \\frac{\\alpha g^2}{\\omega^5} \\exp\\Bigl[ '
      '-0.74\\Bigl\\{\\frac{\\omega\\mathcolor{red}{U_\\omega} '
      '19.5}{g}\\Bigr\\}^{\\!-4}\\,\\Bigr] \n'
      '\\end{align*}\n'
      '\n'
      'Heat Equation:\n'
      '\\[\n'
      ' \\frac{\\partial u}{\\partial t}\n'
      '   = h^2 \\left( \\frac{\\partial^2 u}{\\partial x^2}\n'
      '      + \\frac{\\partial^2 u}{\\partial y^2}\n'
      '      + \\frac{\\partial^2 u}{\\partial z^2} \\right) \n'
      '\\]\n'
      '\n'
      'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Ut purus '
      'elit, vestibulum ut, placerat ac, adipiscing vitae, felis. Curabitur '
      'dictum gravida mauris. Nam arcu libero, nonummy eget, consectetuer id, '
      'vulputate a, magna.\n'
      '\n'
      '\\[\n'
      'E(x, \\xi, t)=\\frac 1{2\\sqrt{\\pi '
      'at}}\\exp\\biggl[-\\frac{(x-\\xi)^2}{4at}\\biggr]\n'
      '\\]\n'
      '\n'
      'Mauris ut leo. Cras viverra metus rhoncus sem. Nulla et lectus '
      'vestibulum urna fringilla ultrices. Phasellus eu tellus sit amet tortor '
      'gravida placerat. Integer sapien est, iaculis in, pretium quis, '
      'viverra\\\\\n'
      '\\textcolor{orange}{\\textbf{Prime Number Theorem}}:\n'
      '\\[\n'
      ' \\int_{1}^{x}\\sum_{p\\le u} \\floor{\\frac{\\log u}{\\log p}} \\log p '
      '\\dd u = \\frac{1}{2\\pi i}\n'
      ' '
      "\\int_{c-i\\infty}^{c+i\\infty}\\frac{x^{s+1}}{s(s+1)}\\left(-\\frac{\\zeta'(s)}{\\zeta(s)} "
      '\\right) \\dd s\n'
      '\\]\n'
      '\n'
      'Mauris ut leo. Cras viverra metus rhoncus sem. Nulla et lectus '
      'vestibulum urna fringilla ultrices. Phasellus eu tellus sit amet tortor '
      'gravida placerat. Integer sapien est, iaculis in, pretium quis, viverra '
      'ac, nunc. Praesent eget sem vel leo ultrices bibendum. Aenean faucibus. '
      'Morbi dolor nulla, malesuada eu, pul.\n'
      '$\\Hom(\\Z_n, S_n)$\n'}